// Re-exporta los íconos compartidos (ver components/iconos.jsx) para no romper los imports
// existentes de `../../components/tenant/iconos` dentro de pages/tenant y components/tenant.
export {
  IcoMas,
  IcoMenos,
  IcoInfo,
  IcoConfiguracion,
  IcoOjo,
  IcoOjoTachado,
  IcoCandado,
  IcoCorreo,
  IcoCheck,
  IcoX,
  IcoChevronAbajo,
  IcoNube,
  IcoSubir,
  IcoPersonas,
  IcoCalendario,
  IcoMoneda,
  IcoReloj,
  IcoDescargar,
  IcoEditar,
  IcoImprimir,
  IcoBasura,
  IcoArchivo,
  IcoArchivoImagen,
  IcoArchivoPdf,
  IcoArchivoWord,
  IcoArchivoExcel,
  IcoArchivoPowerPoint,
  IcoEdificio,
  IcoPausa,
  IcoPlay,
  IcoOpciones,
  IcoEstrella,
  IcoBuscar,
  IcoAlerta,
  IcoTendencia,
} from '../iconos'
